# Generated by Django 3.0.2 on 2020-01-04 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kudos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='body')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('modified_date', models.DateTimeField(verbose_name='modified_date')),
                ('week_year', models.CharField(editable=False, max_length=6, verbose_name='week_year')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos_from_user', to=settings.AUTH_USER_MODEL, verbose_name='from_user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos_to_user', to=settings.AUTH_USER_MODEL, verbose_name='to_user')),
            ],
            options={
                'verbose_name': 'kudos',
                'verbose_name_plural': 'kudos',
            },
        ),
    ]
