# Generated by Django 3.0.2 on 2020-01-07 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0002_auto_20200107_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudos',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 7, 14, 51, 56, 965219), editable=False, verbose_name='created_date'),
        ),
    ]
