# Generated by Django 3.0.2 on 2020-01-10 07:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('kudos', '0004_auto_20200107_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudos',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 13, 3, 1, 737212), editable=False, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='kudos',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos_from_user', to='accounts.UserProfile', verbose_name='from_user'),
        ),
        migrations.AlterField(
            model_name='kudos',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos_to_user', to='accounts.UserProfile', verbose_name='to_user'),
        ),
    ]
