# Generated by Django 3.0.2 on 2020-01-12 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0005_auto_20200110_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudos',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 21, 55, 36, 666255), editable=False, verbose_name='created_date'),
        ),
    ]
