# Generated by Django 3.0.2 on 2020-01-12 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0006_auto_20200112_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudos',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 22, 31, 49, 256479), editable=False, verbose_name='created_date'),
        ),
    ]
