# Generated by Django 3.0.2 on 2020-01-12 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0007_auto_20200112_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudos',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 23, 25, 27, 365879), verbose_name='created_date'),
        ),
    ]
